SELECT CURRENT_DATE() FROM DUAL;

SELECT CURRENT_TIME()  FROM DUAL;

SELECT CURRENT_TIMESTAMP()  FROM DUAL;

CREATE TABLE MES(
	id INT,
	content VARCHAR(30),
	send_time DATETIME);
	
INSERT INTO mes
	VALUES(1,'北京新闻',CURRENT_TIMESTAMP());
INSERT INTO mes
	VALUES(2,'上海新闻',NOW());
INSERT INTO mes
	VALUES(3,'冠州新闻',NOW());

SELECT * FROM mes;
SELECT NOW() FROM DUAL;

SELECT id,content,DATE(send_time)
	FROM mes;

SELECT *
	FROM mes
	WHERE DATE_ADD(send_time,INTERVAL 10 MINUTE) >= NOW();
	
SELECT *
	FROM mes
	WHERE DATE_SUB(NOW(),INTERVAL 10 MINUTE) <= send_time;
SELECT *
	FROM mes
	WHERE send_time >= DATE_SUB(NOW(),INTERVAL 20 MINUTE);
	
SELECT DATEDIFF('2011-11-11', '1990-01-01') /365 FROM DUAL;

SELECT DATEDIFF(NOW(), '1986-11-11')/365 FROM DUAL;

SELECT DATEDIFF(DATE_ADD('1987-11-11',INTERVAL 80 YEAR),NOW())
	FROM DUAL;
	
SELECT DATEDIFF(DATE_ADD('2000-12-03',INTERVAL 80 YEAR),NOW())
	FROM DUAL;

SELECT TIMEDIFF('10:19:60','04:35:56') FROM DUAL;

SELECT YEAR(NOW()) FROM DUAL;


SELECT MONTH(NOW()) FROM DUAL;

SELECT DAY(NOW()) FROM DUAL;

SELECT YEAR('2015-12-12') FROM DUAL;

SELECT UNIX_TIMESTAMP()/(24*3600*365) FROM DUAL;

SELECT FROM_UNIXTIME(1618483484,'%y-%m-%d') FROM DUAL;
SELECT FROM_UNIXTIME(1618483000,'%y-%m-%d %h:%i:%s') FROM DUAL;