SELECT ABS(10) FROM DUAL;
SELECT ABS(-10) FROM DUAL;

SELECT 10 FROM DUAL;
SELECT BIN(10) FROM DUAL;

SELECT CEILING(1.1) FROM DUAL;
SELECT CEILING(-1.1) FROM DUAL;

SELECT CONV(8,10,2) FROM DUAL;
SELECT CONV(8,16,2) FROM DUAL;
SELECT CONV(8,16,10) FROM DUAL;

SELECT FLOOR(1.1) FROM DUAL;
SELECT FLOOR(-1.1) FROM DUAL;


SELECT FORMAT(78.25534,2) FROM DUAL;

SELECT LEAST(0,1,-10,4) FROM DUAL;

SELECT MOD(10, 3) FROM DUAL;

SELECT RAND(3) FROM DUAL;
SELECT RAND() FROM DUAL;
